export const REDUX_GET_ALL_ARTICLES = "REDUX_GET_ALL_ARTICLES";
export const REDUX_GET_ALL_ARTICLES_ERROR = "REDUX_GET_ALL_ARTICLES_ERROR";
export const REDUX_GET_ARTICLE_BY_ID = "REDUX_GET_ARTICLE_BY_ID";
export const REDUX_GET_ARTICLE_BY_ID_ERROR = "REDUX_GET_ARTICLE_BY_ID_ERROR";